### ISSUE TITLE
Execution issue: n.durationBetween is not a function

### ISSUE THREAD

**Issue by nmorasb** [projecttacoma/fqm-execution#195] opened 2023-02-02 16:56 UTC
We are seeing an error when calling fqm-execution with the measure bundle and patient bundle attached.
![Screen Shot 2023-02-02 at 11 40 39 AM](https://user-images.githubusercontent.com/94391996/216386730-1bd68656-2b93-4f76-bde0-688600bca06b.png)

We are seeing this with v1.0.2, v1.0.4 and v1.0.5. (v1.0.3 was not specifically tested).

Please let us know if you need any other info or resources, thanks!
[durationBetween-issue.zip](https://github.com/projecttacoma/fqm-execution/files/10571388/durationBetween-issue.zip)

**Comment by mgramigna** [comment] 2023-02-02 21:53
Hi @nmorasb, thanks for the issue.

A stack trace like this usually leads us to `cql-execution` and eventually to the ELM itself. "durationBetween is not a function" means that the left hand side of that invocation is not a CQL Date or DateTime type. After some brief debugging, the engine is indeed not receiving either of those types, specifically for the patient's birthDate property. Here is the relevant CQL snippet from your measure:

``` cql
/* From library PCMaternal version '5.0.000' */
define "Encounter with Age Range":
  ["Encounter": "Encounter Inpatient"] EncounterInpatient
                      where EncounterInpatient.status = 'finished'
 /* causes error --> */ and AgeInYearsAt(date from start of EncounterInpatient.period) in Interval[ 8, 65 )
                        and EncounterInpatient.period ends during day of "Measurement Period"
```

I took a look at the corresponding ELM, specifically around the birthDate property expression (snipped for brevity):

```
{
  "localId": "28",
  "locator": "35:29-35:86",
  "resultTypeName": "{urn:hl7-org:elm-types:r1}Integer",
  "precision": "Year",
  "type": "CalculateAgeAt",
  "operand": [
    {
      "path": "birthDate",
      "type": "Property",
      "source": {
        "name": "Patient",
        "type": "ExpressionRef"
      }
    },
    // snip

}
```

Per the [CQL spec](http://cql.hl7.org/04-logicalspecification.html#calculateageat), the only valid signatures for `CalculateAgeAt` are `(Date, Date)` and `(DateTime, DateTime)`. I would expect the above expression to be surrounded with a `FHIRHelpers.ToDate` call (that the translator should be inserting during translation) to ensure that the signature is satisfied. This is what I've seen in other chunks of ELM:

Snipped from MATGlobalCommonFunctionsFHIR4 version 6.1.000:

```
{
  "localId": "316",
  "locator": "215:8-215:44",
  "name": "ToDate",
  "libraryName": "FHIRHelpers",
  "type": "FunctionRef",
  "operand": [
    {
      "localId": "315",
      "locator": "215:27-215:43",
      "path": "birthDate",
      "type": "Property",
      "source": {
        "localId": "314",
        "locator": "215:27-215:33",
        "name": "Patient",
        "type": "ExpressionRef"
      }
    }
  ]
}
```

Having a `FHIRHelpers.ToDate` call in the ELM will resolve this issue. We should confirm if this is an error in the translator with @brynrhodes before proceeding anywhere in cql-execution.

**Comment by p9g** [comment] 2023-02-03 16:26
Initiated by https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1343

**Comment by brynrhodes** [comment] 2023-02-07 18:42
I've extracted the contents of the attached bundles and tested them in the current version of the VSCode translator (2.4.0) and it does produce ELM that correctly accesses the birthDate (either using a FHIRHelpers, or by accessing the `value` property, depending on how it's referenced).

**Comment by brynrhodes** [comment] 2023-02-07 18:43
I do know that this is an issue that was recently addressed, so my guess is that the version of the translator producing the ELM that is causing the issue is one that still had that issue.

**Comment by brynrhodes** [comment] 2023-02-07 18:50
Here is the issue: https://github.com/cqframework/clinical_quality_language/issues/822, and it was included in translator release 2.4.0: https://github.com/cqframework/clinical_quality_language/releases/tag/v2.4.0

**Comment by JSRankins** [comment] 2023-02-08 14:01
MADiE is currently on Translator v2.4.0 - has been since Jan 11 release (MADiE v1.0.3) - https://www.emeasuretool.cms.gov/sites/default/files/2023-01/MADiE%201.0.3%20Release%20Notes.pdf. @mgramigna , possible that this issue occurs in an earlier version of fqm-execution? MADiE is currently on fqm-execution v1.0.2.

**Comment by mgramigna** [comment] 2023-02-08 14:24
> MADiE is currently on Translator v2.4.0 - has been since Jan 11 release (MADiE v1.0.3) - https://www.emeasuretool.cms.gov/sites/default/files/2023-01/MADiE%201.0.3%20Release%20Notes.pdf. @mgramigna , possible that this issue occurs in an earlier version of fqm-execution? MADiE is currently on fqm-execution v1.0.2.

@JSRankins this issue is independent of fqm-execution. The ELM causes an issue even when calculating the raw results of the engine with cql-execution.

I tried translating the ELM directly, both in VS Code extension and locally with the CQL to ELM CLI, and I still haven't seen proper output with translator 2.4.0. @brynrhodes -- are we missing something? What is the expected ELM for this? I see 

```
{
  "path": "value",
  "type": "Property",
  "source": {
    "path": "birthDate",
    "type": "Property",
    "source": {
      "name": "Patient",
      "type": "ExpressionRef"
    }
  }
}
```

So accessing birthDate.value on the Patient. Is this an intended difference to not use FHIRHelpers.ToDate?

**Comment by mgramigna** [comment] 2023-02-08 14:38
I re-translated the posted measure locally and re-ran it through fqm-execution without changing anything and the error no longer happens.

**Comment by srankins** [comment] 2023-02-08 14:39
Hi @mgramigna. I'm just throwing out ideas. Sounds like Bryn is saying that the ELM issue is fixed in 2.4.0, which is what was in use by MADiE when this issue was encountered by the user. The issue was encountered while running fqm-execution. Since you were able to recreate against ELM JSON generated by Translator 2.4.0, this is the source of my confusion.

**Comment by mgramigna** [comment] 2023-02-08 14:46
> Hi @mgramigna. I'm just throwing out ideas. Sounds like Bryn is saying that the ELM issue is fixed in 2.4.0, which is what was in use by MADiE when this issue was encountered by the user. The issue was encountered while running fqm-execution. Since you were able to recreate against ELM JSON generated by Translator 2.4.0, this is the source of my confusion.

My confusion is that I don't think the ELM posted in the attached measure bundle was actually translated using 2.4.0.  On the left is the ELM on the Measure attached to this issue, on the right is the measure translated with 2.4.0

![image](https://user-images.githubusercontent.com/16297930/217563245-3214338c-6e4d-4244-a768-9bace14e0332.png)

The ELM on the left throws an error during execution, the ELM on the right doesn't

**Comment by srankins** [comment] 2023-02-08 14:52
@nmorasb will need to comment/provide update. I just know that @p9g reported issue, and his measure would have been using 2.4.0 Translator. Refer to https://oncprojectracking.healthit.gov/support/browse/BONNIEMAT-1343.

**Comment by mgramigna** [comment] 2023-02-08 14:56
If it helps, here's a full diff of the ELM side by side (link expires in 24h): https://www.diffchecker.com/Ks0HVrlX/

left is extracted from PCMaternal in the posted measure bundle, right is PCMaternal translated using cql-to-elm CLI 2.4.0

**Comment by mgramigna** [comment] 2023-02-15 15:35
Per discussion yesterday, closing due to translator version issue identified in a dependent library

**Closed by mgramigna** 2023-02-15 15:35 UTC
Labels: translator
